### ISSUE TITLE
800 - Caribbean islands have their modern names

### ISSUE THREAD

**Issue by temefleet** [nrgapple/historic-country-borders-app#10]
First of all, great work.

As I was exploring through time I noticed from the year 800 some of the Caribbean are named after the modern country...Jamaica, Cuba, Puerto Rico, DR. My knowledge of history isn't great, but this doesn't seem right.

**Comment by nrgapple** [comment]
Hey thanks for letting me know. You should put it a pr for this change over at https://github.com/aourednik/historical-basemaps. Or open an issue there!
