### ISSUE TITLE
1492 China

### ISSUE THREAD

**Issue by timmhayes** [nrgapple/historic-country-borders-app#9]
Cool app, thanks! I noticed your borders for Laos in 1492 extend across China, but I'm pretty sure that should be labeled as the Ming dynasty. I realize this is not your data though, so I posted the issue on your source repo: https://github.com/aourednik/historical-basemaps/issues/12

**Comment by timmhayes** [comment]
I fixed this bug in the source repo at the request of aourednik, but I guess you need to do a refresh of historicborders-timeline-example for it to apply here. Once you do, you should see the Ming Empire over China in 1492 (replacing "Laos").

**Comment by nrgapple** [comment]
Thanks a lot! I moved it back to aourednik. You should see it now. Thanks for helping out!
